### PR TITLE
Added support for moving the launcher to the bottom

### PR DESCRIPTION
**Pull request by Seth-Johnson**
Unity in 16.04 introduces the ability to move the launcher to the bottom of the screen. This adds support for this in UTT.  

anim

### CODE REVIEW

**Comment by jokerdino** [comment]
Looks good. Merging the PR.

**Comment by phanimahesh** [comment]
Thankyou @Seth-Johnson! This is great!

**Comment by phanimahesh** [comment]
Even though I never got to officially complete the grand rewrite ( getting rid of spaghetti everywhere ), this is one of those pieces I like. A lot. The new format is declarative, and makes contributions super easy,

**Comment by Seth-Johnson** [comment]
I'm glad you like it @phanimahesh :)

Yes, the new format is very easy to update, which is great! It makes it easy for anyone to help keep UTT up to date.

I have one question though: When you run UTT with the new code on a pre 16.04 release (one that doesn't support moving the launcher) the radio buttons get greyed out properly, but the label does not. I couldn't figure out why that was. Did I miss a property on the label or something?

**Comment by phanimahesh** [comment]
That is strange, I couldn't see any difference between the declaration for Visibility and Position, but probably I haven't compared them carefully enough. I'll have a closer look at it later today.

**Pull request merged**
