### PR TITLE
Add missing dependency

### PR DESCRIPTION
**Pull request by benjaoming**
https://bugs.launchpad.net/unity-tweak-tool/+bug/1444315

### CODE REVIEW

**Comment by phanimahesh** [comment]
I remember we added and then removed this, for some reason. /cc @jokerdino Do you remember why?

Given that the package is available in all supported versions, I see no harm in adding it, it should fix the crashes.

**Comment by phanimahesh** [comment]
@benjaoming Thanks for the quick fix. The PPA will be updated in the next scheduled rebuild, within 24 hours.

**Comment by jokerdino** [comment]
I remember either adding it as dependency or at least thinking of adding it. Unfortunately, I can't find anything regarding it. For the time being, good move to merge the PR. +1

**Comment by benjaoming** [comment]
You're most welcome! Unfortunately I didn't learn a lot of BZR stuff by going the Github way :)

Great project btw!! Really removes a lot of problems. For instance, when you have a slow internet connection or lot's of busy processes and the dash decides to look up a million things online and scan the hard drive... so basically, I use it to disable crap in Unity.. you should call the project unity-disable-stuff :D

**Comment by xeron** [comment]
I'm not saying that this PR is wrong, but:

```
$ sudo apt-get install unity-tweak-tool 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libaccounts-qt5-1 libandroid-properties1 libdouble-conversion1v5 libhud2 liboxideqt-qmlplugin liboxideqtcore0 liboxideqtquick0 libqt5feedback5 libqt5multimedia5 libqt5organizer5 libqt5positioning5 libqt5qml5 libqt5quick5
  libqt5quicktest5 libqt5test5 libqt5xml5 libsignon-qt5-1 libubuntugestures5 libubuntutoolkit5 libunity-action-qt1 libunity-webapps0 qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings qml-module-qtfeedback
  qml-module-qtgraphicaleffects qml-module-qtquick-layouts qml-module-qtquick-window2 qml-module-qtquick2 qml-module-qttest qml-module-ubuntu-components qml-module-ubuntu-layouts qml-module-ubuntu-onlineaccounts
  qml-module-ubuntu-performancemetrics qml-module-ubuntu-test qml-module-ubuntu-web qtdeclarative5-accounts-plugin qtdeclarative5-qtquick2-plugin qtdeclarative5-ubuntu-ui-toolkit-plugin qtdeclarative5-unity-action-plugin
  suru-icon-theme ubuntu-mobile-icons ubuntu-ui-toolkit-theme unity-webapps-common unity-webapps-qml unity-webapps-service webapp-container webbrowser-app
Suggested packages:
  xul-ext-unity | unity-chromium-extension qtdeclarative5-online-accounts-client0.1 qtdeclarative5-ubuntu-content1 qtdeclarative5-ubuntu-download-manager0.1 qml-module-ubuntu-onlineaccounts-client
The following NEW packages will be installed:
  libaccounts-qt5-1 libandroid-properties1 libdouble-conversion1v5 libhud2 liboxideqt-qmlplugin liboxideqtcore0 liboxideqtquick0 libqt5feedback5 libqt5multimedia5 libqt5organizer5 libqt5positioning5 libqt5qml5 libqt5quick5
  libqt5quicktest5 libqt5test5 libqt5xml5 libsignon-qt5-1 libubuntugestures5 libubuntutoolkit5 libunity-action-qt1 libunity-webapps0 qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings qml-module-qtfeedback
  qml-module-qtgraphicaleffects qml-module-qtquick-layouts qml-module-qtquick-window2 qml-module-qtquick2 qml-module-qttest qml-module-ubuntu-components qml-module-ubuntu-layouts qml-module-ubuntu-onlineaccounts
  qml-module-ubuntu-performancemetrics qml-module-ubuntu-test qml-module-ubuntu-web qtdeclarative5-accounts-plugin qtdeclarative5-qtquick2-plugin qtdeclarative5-ubuntu-ui-toolkit-plugin qtdeclarative5-unity-action-plugin
  suru-icon-theme ubuntu-mobile-icons ubuntu-ui-toolkit-theme unity-tweak-tool unity-webapps-common unity-webapps-qml unity-webapps-service webapp-container webbrowser-app
0 upgraded, 48 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/43.4 MB of archives.
After this operation, 154 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
```

Wow wow wow, really?

**Comment by phanimahesh** [comment]
Did you try `--no-install-recommends --no-install-suggests` ? Our direct dependencies are few in number.

**Comment by xeron** [comment]
I tested with `--no-install-recommends` and result was the same. I believe this dependencies are from `unity-webapps-common`.

**Comment by xeron** [comment]
Same result with `--no-install-recommends --no-install-suggests`.

**Comment by phanimahesh** [comment]
Ah, okay. But `unity-webapps-common` should be installed by default, right? Do you have an unusual setup?

**Comment by xeron** [comment]
Yes, this is correct. I remove a lot of things which I don't use.

**Comment by Seth-Johnson** [comment]
The correct approach to this is not crash if the webapps schemas are missing. Should probably plan that for 0.0.8. btw, I'm pretty sure unity-webapps-services provides the schemas not unity-webapps-common (which depends on the services package). That would be a good workaround in the meantime.

**Comment by xeron** [comment]
`unity-webapps-service` depends on `webapp-container` so it won't help and it will require to install all this packages anyway.

**Comment by Baltix** [comment]
Should I report separate bug about possibility to work without unity-webapps installed?
Seth-Johnson commented on 15 Apr
> The correct approach to this is not crash if the webapps schemas are missing

**Comment by Seth-Johnson** [comment]
I believe that it has already been reported on Launchpad.

**Pull request merged**
